@startuml Diagram
left to right direction

rectangle "Sprint 3" {
    Add -- (View Customer Location)
    Add -- (Confirm or Edit Estimated Price)
    Add -- (Track Service Requests)
    Add -- (Send Notifications)
}

@enduml